# General Settings
name: Davide Barranca
job_title: Photoshop, etc.
email: davide.barranca@gmail.com
description: Digital Caveman. Photoshop retoucher and script/panels developer. I am also an author, check the Courses page!
avatar: /assets/img/io.jpg
favicon: /favicon.ico
twitter_handler: undavide
analytics_code: UA-25716894-1
disqus: davidebarranca

exclude:
  - .jekyll-cache

# Social Accounts
social_networks:
-  { name: facebook, url: 'https://www.facebook.com/undavide' }
-  { name: twitter, url: 'https://twitter.com/undavide' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/undavide' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
# url: "https://elegant-davinci-7a1889.netlify.com"
url: "https://www.davidebarranca.com"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 20
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->
kramdown:
  input: GFM
  coderay_default_lang: js
highlighter: rouge
default_lang: js

# Plugins
plugins:
  - jekyll-gist
  - jekyll-sitemap

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed
